# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [7]:
vec10= np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [10]:
vec2=np.arange(10,49)

4. Find the shape of previous array in question 3

In [13]:
np.shape(vec2)

(39,)

5. Print the type of the previous array in question 3

In [15]:
vec2.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [18]:
np.version.version

'1.18.1'

7. Print the dimension of the array in question 3


In [16]:
vec2.ndim

1

8. Create a boolean array with all the True values

In [29]:
a1=np.ones(2)
print(a1)

[1. 1.]


9. Create a two dimensional array




In [32]:
a2d=np.array([[1,2],[3,4]])
a2d

array([[1, 2],
       [3, 4]])

10. Create a three dimensional array



In [36]:
a2d=np.array([[[1, 2],[3, 4]],[[5,6],[7, 8]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [42]:
vec3=np.flipud(vec2)
vec3

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [43]:
vec10= np.zeros(10)
vec10[4]=1
vec10

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [45]:
id_x=np.identity(3)
id_x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [46]:
arr5 = np.array([1, 2, 3, 4, 5])
float_arr5=arr5.astype(np.float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [47]:
rr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
ans=rr1*arr2
ans

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [67]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3=np.array([[0., 0., 0.],

            [0., 0., 0.]]) 

for i in range(2):
     for j in range(3):
          if(arr1[i][j]>arr2[i][j]):
                arr3[i][j]=arr1[i][j]
arr3
    

array([[1., 0., 3.],
       [0., 5., 0.]])

17. Extract all odd numbers from arr with values(0-9)

In [69]:
odd_num=list()
for i in range(2):
         for j in range(3): 
            if(arr3[i][j]%2 !=0 and arr3[i][j]<10):
                odd_num.append(arr3[i][j])
odd_num

[1.0, 3.0, 5.0]

18. Replace all odd numbers to -1 from previous array

In [70]:
for i in range(2):
         for j in range(3): 
            if(arr3[i][j]%2 !=0):
                arr3[i][j]=-1
arr3

array([[-1.,  0., -1.],
       [ 0., -1.,  0.]])

In [72]:
arr = np.arange(10)
arr[5]=1
arr[6]=1
arr[7]=1

20. Create a 2d array with 1 on the border and 0 inside

In [77]:
arr1 = np.array([[1., 1., 1.],

            [1., 0., 1.],
            [1., 1., 1.]]
               ) 
arr1

2

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [79]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [80]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d=arr3d.astype(np.int64)

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [86]:
arr2d=np.arange(10).reshape(2,5)
arr2d[0:1,0:]

array([[0, 1, 2, 3, 4]])

In [87]:
arr2d=np.arange(10).reshape(2,5)
arr2d[1:,0:]

array([[5, 6, 7, 8, 9]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [88]:
arr2d=np.arange(10).reshape(2,5)
arr2d[0:,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [92]:
arr1=np.random.randint(5,20,(10,10))
np.min(arr1)
np.max(arr1)

19

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [95]:
a= np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=list()
for i in a:
    for j in b:
        if(j==i):
            c.append(i)
c

[2, 2, 2, 2, 4, 4, 4, 4]

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [107]:
a= np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.zeros(10)
count=0
for i in a:
    for j in b:
        if(i==j):
            c[count]=1
    count=count+1
count=0
for i in b:
    for j in a:
        if(i==j):
            c[count]=1
    count=count+1


            

array([0., 1., 0., 1., 0., 1., 0., 1., 0., 0.])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [112]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
count=0
for n in names:
    if(n!="Will"):
        print(data[count:count+1,0:])
    count+=1   
        

[[-1.14964933 -0.09732395  0.47139081  0.54375564]]
[[-0.76650257 -0.10456523 -0.13329392  0.70984513]]
[[ 1.16532499  0.25579654 -1.19460061 -0.98891888]]
[[ 1.36784047  0.92724394 -0.28686076  0.19317982]]
[[ 2.5308399   1.26528318 -0.18069639  1.18114679]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
count=0
for n in names:
    if(n!="Will"):
        print(data[count:count+1,0:])
    count+=1
for n in names:
    if(n!="Joe"):
        print(data[count:count+1,0:])
    count+=1

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [116]:
arr2d=np.arange(15.0).reshape(5,3)
arr2d


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [117]:
arr2d=np.arange(16.0).reshape(2,2,4)
arr2d

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

33. Swap axes of the array you created in Question 32

In [118]:
arr2d=np.arange(16.0).reshape(4,2,2)
arr2d

array([[[ 0.,  1.],
        [ 2.,  3.]],

       [[ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [126]:
import math
arr2d=np.arange(16.0)
print(arr2d)
count=0
for i in arr2d:
    arr2d[count]=math.sqrt(i)
    if(arr2d[count]<0.5):
        arr2d[count]=0
    count+=1
arr2d
    

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [128]:
arr1=np.random.randint(0,12)
arr2=np.random.randint(0,12)

if(np.max(arr1)>np.max(arr2)):
    f=np.max(arr2)
    s=np.max(arr1)
else:
    f=np.max(arr1)
    s=np.max(arr2)
arr3=np.arange(f,s)
arr3

array([0, 1])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [141]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique=list()
flag=0
for i in names:
    for j in names:
        if(i==j):
            if(i not in unique):
                     unique.append(i)
unique
            

['Bob', 'Joe', 'Will']

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [18]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
flag=0
count=0
for i in a:
    for j in b:
        if(i==j):
            c=np.delete(a,count)
            
    count+=1
c
            

[1 2 4 5]
[1 2 3 4]


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [3]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum